input_image_size : [512, 512]
input_image_channels : 3
input_image_format : "BRG"
input_image_type : "uint8"

image_encoder_type : "resnet34"

measurement_encoder_input_dimension : 1
measurement_encoder_hidden_layer_dimensions:
  - 512
  - 512
measurement_encoder_output_dimension : 512
measurement_encoder_hidden_activation : "relu"
measurement_encoder_final_activation : "relu"

speed_encoder_input_dimension : 1000
speed_encoder_hidden_layer_dimensions:
  - 512
  - 512
speed_encoder_output_dimension : 1
speed_encoder_hidden_activation : "relu"
speed_encoder_final_activation : "relu"


branched_encoder_input_dimension : 1512
branched_encoder_hidden_layer_dimensions:
  - 512
  - 512
branched_encoder_output_dimension : 2
branched_encoder_hidden_activation : "relu"
branched_encoder_final_activation : "tanh"

number_of_commands : 4
learning_rate : 0.0001
loss_weight : 0.7
num_epochs : 10
batch_size : 512
save_path : "cilrs_model_epoch_10_resnet_34"
